Joshimuz/mcbingo

.github/ISSUE_TEMPLATE/new-goal-suggestion.md
bingo.js

Usage of RegExp to parse the query part of the URL has been replaced with [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).
I've manually tested this change in Firefox 85 and Chromium 88, by comparing local to [minecraftbingo.com](https://minecraftbingo.com).

Simpify parsing of query part of URL

---

goals_v4.js

Fix capitalization of the word "Pillager" in the tooltip text of the goal "Disarm a Pillager".

fix capitalization in "Pillager"

---

goals_v4.js

Remove a curly quotes character which may not be visible in browsers,
depending on encoding settings,  from the string 'name' of the "Ominous
Banner" goal.  This character [appears as "â€Œ" in some encodings](https://stackoverflow.com/a/48046018/1083697). This
is the only instance, that I found.
----
The broken name in `/index.html?s=3-0-0-dev_89078` looks like this:

clean up name of the "Ominous Banner" goal

---

index.html

The new rules are good, but I think it could use some improvements:
* The version section has "designed for" twice, so combined that into one sentence.
* The description of the different types of goals a bit less cluttered. A proper list, instead of just list items. Having headings for the different types makes sense, but I think having one list item for each type makes it more readable.
* Adding headings for the other sections, moved some stuff around that belongs logically together (e.g. tips for marking goals should be next to the section about goals).
* Too many "Tips" and "Notes" that they kind of loose some meaning of "look, this is important", so removed some of these prefixes or integrated the information otherwise.

Reformatted rules

---

bingo.css
bingo.js
generator_v1.js
generator_v2.js
generator_v3.js
goals_v1.js
goals_v2.js
goals_v3.js
goals_v4.js

The last commit of this pull ruquest fixes a bug introduced in fa40258 (currently in `dev`, but not in `master`). Other commits are code cleanup and refactoring. See also https://clips.twitch.tv/ObservantSuspiciousBunnySquadGoals-IgoZFMA-alnr5UWe
Steps to reproduce the bug:
1. Open a URL with a hidden table setting, for example `index.html?s=4-1-0-dev_89001`
2. Click "Show Table"
3. Observe the squares which are supposed to have tooltips, e.g. "Activate a 5x4 Nether Portal (not counting corners)"

Overhaul tooltip icon visibility

---

goals_v4.js

Zombie Pigmen were renamed to Zombified Piglins in the "Nether Update".
- https://www.minecraft.net/en-us/article/everything-we-announced-minecon-live-2019
- https://minecraft.gamepedia.com/Nether_Update

Fix reference to Zombified Piglins in goals_v4.js

---

bingo.js

A bug was introduced in commit 48ce64b (hide .tooltipQ using CSS attribute rule, 2021-03-07):
1. Generate random seed until a goal with a tooltip appears.
2. Hover over a tooltip. Remember the position of the square.
3. Generate random seeds until another sheet with a tooltip in the same square appears.
4. Hover over the tooltip in the same square as in step #2.
5. Click "export the current sheet as JSON"
6. Observe the tooltip for the same square in the export.
- In steps 4 and 6 the tooltip corresponds to the goal from the second step.
- In steps 4 and 6 the tooltip corresponds to the goal of the shown square.
Here's a patch which makes testing easier: [testing-tooltips.patch.txt](https://github.com/Joshimuz/mcbingo/files/6098110/testing-tooltips.patch.txt). It adds a button "Debug …

Fix tooltips not updating

---

bingo.css

Only the first CSS selectors of CSS rules for the rules `<section>` have been created with the #rules-section selector, which might cause issues in the future.
Add missing selectors to make the rules more specific.  Move `<li>` tag specific declaration into a separate CSS rule.  Reorder rules, so that `<h2>` and `<h3>` rules are higher than `<ul>` rules.  Note, that this doesn't change the design of the page, just makes the CSS more robust to possible future additions of affected tags.

Clean up CSS for #rules-section

---

index.html

Per [jQuery blogpost](https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/) it is not recommended to use the file     `jquery-latest.js`.  Switch explicitly to jQuery 1.11.1 for now, which is identical to the currently used `jquery-latest.js`, which was frozen by the jQuery project at version 1.11.1.
Quotes from blog post:
> So let’s be clear: Don’t use jquery-latest.js on a production site.
> [...]
> As jQuery adoption has continued to grow, even that safeguard seems insufficient to protect against careless use of http://code.jquery.com/jquery-latest.js. So we have decided to stop updating this file, as well as the minified copy, keeping both files at version 1.11.1 forever.
> [...]
> However, note that [jquery-latest.js] currently has a very short cache time, which means you’re …

Use jQuery version 1.11.1 explicitly

---

bingo.js

Goals with tag "Never" are always completed at the very start at the
game.  Playtesting has shown that players sometimes don't notice the
"Never" goals and lock themselves out of them before reading the sheet
completely.
Most people use green to signify completion of a goal.  So highlight all
the "Never" goals as if they are already completed when the sheet is
generated.  Another argument for the green colour is that it is the
colour available in all colour count options.
----
Demo:
https://user-images.githubusercontent.com/624072/110696541-809cf600-81eb-11eb-9fee-3bb33070d367.mp4

function generateNewSheet() has been taught to highlight "Never" goals at the start

---

generator_v3.js

This change doesn't affect sheet generator. This is a simple code cleanup for 20% faster sheet generation. Doesn't matter for users, but matters when generating sheets for every seed and difficulty. On my laptop, current version (branch `dev`) of `generator_v3.js` takes 330.2 seconds to gather statistics for all goals in every seed and difficulty. With this optimization, it takes 248.8 seconds.
I hope that this also makes usage `var cont` easier to understand – as soon as one of the "good goal" conditions is violated, bail out.

generator_v3.js has been optimized

---

goals_v4.js

Very Easy. Sticks and wool [1] are easily available.  Anti Synergy with
the Easy goal "Hang up 3 Different 4x4 Paintings", so that two
"Paintings" goals don't show up on an Easy sheet.  This Goal is good,
because it fits the difficulty and it is not an Item goal.
[1] see current crafting recipe:
https://minecraft.gamepedia.com/Painting?oldid=1872933#Crafting

goals_v4: add Very Easy goal "Hang up a Painting"

---

bingo.js

Change width and height of the window popout in Streamer Mode to hide scrollbars

---

bingo.css
bingo.js
index.html

Commit ce80d9d fixes the `border-radius` for tooltips:
Commit 124dc57 makes the "Copy Seed" buttons look like other buttons in the UI.
Tooltips on clicking the buttons have been added in commit 0db4326:
Tooltips on hover have been added in commit 25ee363:
The other commits are refactoring.

Tooltips have been added to the "Copy Seed" buttons

---

bingo.js
generator_v1.js
generator_v2.js
generator_v3.js
index.html

Main change of the pull request is in commit c3a4318.
----
- I have tested every invocation of jQuery's `$` function in Firefox 86 and Chromium 89.
- I checked every release in [deprecation notes](https://api.jquery.com/category/deprecated/) – mcbingo doesn't use any deprecated functions. 
- I skimmed through [jQuery upgrade guides](https://jquery.com/upgrade-guide/). The only thing relevant to mcbingo was [a recommendation about `.show()` function](https://jquery.com/upgrade-guide/3.0/#breaking-change-show-hide-and-toggle-methods-now-respect-more-stylesheet-changes):
> Further, while `.show()` and similar calls will continue to force visibility of elements that are hidden by stylesheet rules, supporting this functionality slows down all show/hide operations and its use is not …

Version of jQuery has been upgraded to 3.6.0

---

goals_v4.js

Add missing word "can" in the tooltip of the "Never smelt with Furnaces" goal in `goals_v4.js`.

Wording cleanup

---

generator_v3.js

generator_v3 keeps track of antisynergys, reactants, and catalysts on
the sheet using three arrays.  Logic for all three of those requires a
unique set of strings, and two of these arrays (reactants and catalysts)
are deduplicated for every generated goal.
So use the [`Set` type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) for keeping track of antisynergys, reactants, and
catalysts of goals, already added to the sheet.
Fix the spelling in comments, while we're here.

generator_v3 has been refactored to use Sets

---

bingo.css

- File `bingo.css` has been reorganised. Commits, which reorder the rules, are best viewed using [`--color-moved` option of `git show`](https://git-scm.com/docs/git-show#Documentation/git-show.txt---color-movedltmodegt).
- CSS rules for sliders have been refactored – this is in preparation for #106.
- Background texture for "Show Table" button has been fixed:
- Font Minecraftia has been applied to more elements:
1. Version select:
2. Streamer mode links (with lighter colour than before): 
3. Header and "Hide" link in export dialog:

CSS tweaks & cleanup

---

bingo.js

A fix for a bug introduced in #113.
Before:
https://user-images.githubusercontent.com/624072/112728161-252a7200-8f26-11eb-954b-98bf53a368b1.mp4
After:

Calculation of the position for the "Copied!" tooltip has been fixed

---

bingo.css
bingo.js
index.html

This allows for the seed input located directly below the sheet to be editable, as it is inconvenient to do so while the sheet is popped out.

bingo.js: Make readonly seed input below sheet editable

---

.github/FUNDING.yml

Add two links to the landing page of the GitHub repository.  First link
is for donations, second link -- for Twitch subscription.  The links are
displayed in the "Sponsor this project" block in the sidebar on the
right.  GitHub documentation about the sponsor buttons:
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository
----
It would look like this:
You can see how it looks and works at https://github.com/rybak/mcbingo which at the moment has this commit merged into `master` branch.

GitHub: add "Sponsor this project" links

---

generator_v3.js

Since commit b712eea (Version 4 preperations, 2021-03-22), `generator_v3`
has been used in version 4 of Minecraft Bingo.  Version 4 is marked as
stable, so goal generation done by `generator_v3` should not change.
Update the top comment in `generator_v3.js` to reflect that.

generator_v3: update top comment

---

bingo.css
bingo.js

Several fixes for minor glitches.
----
First commit fixes a glitch, where the export popup flashes for a split second during page load. This is how the glitch looks like without the fix:
[demo of export popup flash glitch ](https://user-images.githubusercontent.com/624072/221416292-0463982f-fcd0-43fc-9933-e10700be3a97.webm)
----
Second commit simplifies JS by moving tooltip hiding to CSS. It's not visible during regular use, but here's how tooltips look at the bottom of the site with disabled JavaScript, just for fun:
----
Third commit fixes backgrounds on monitors wider than 1920p:
----
Fourth commit fixes z-index glitch between export popup and options menu and sliders. It's easy to get the slider glitch in regular use – just scroll all the way up while export is showing:
But a bit …

Various CSS fixes

---

goals_v4.js
goals_v5.js

Fix for a tag bug [discussed in Discord](https://discord.com/channels/131720430326120449/1045020502621691985/1160398977141846026). Details are in the commit messages.

goals_v5: add Overworld tag to potions

---

bingo.css
index.html

Alright, let's try this again.
This PR adds a way to display if a seed is too long for the seed box.
It changes the overall look somewhat, since it introduces a linebreak between the seed and difficulty value.
The seed box will now grow with the seed but not overflow anymore.
This is what it looked like before:
This is what it looks like after my PR:

Handling seeds of arbitrary length in UI
