Joshimuz/mcbingo

bingo.css
Changes to the Generate new Seed Button
And changes to the tooltip window
=> Changes to the CSS

goals_v1.js, goals_v2.js, goals_v3.js, goals_v4.js
I noticed that not every instance was fixed in 37cbb64c719a. I found these using `git grep -i "it's"`.
=> use possesive pronoun "its" correctly

index.html
Made some changes to the new text in `index.html` including grammar, typos and consistent stylistics.
=> Change text on index for consistency

bingo.css, bingo.js
This PR is just several unrelated cleanups in CSS code.
----
All changes were tested in Firefox 86.0 and Chromium 89.0.
=> CSS cleanup

index.html
This PR is just several unrelated cleanups in HTML code.
----
All changes were tested in Firefox 86.0 and Chromium 89.0.
=> HTML cleanup

bingo.css, bingo.js, index.html
Most of the commits are just refactoring, which doesn't change how the webpage looks or behaves.
* 1a2406e css: fix vertical misalignment of text on buttons – fixes [a visual glitch](https://user-images.githubusercontent.com/624072/110212966-355aae80-7e9e-11eb-90bf-d2ac2c9fb398.png) in buttons.
* 1c499d6 css: justify buttons using flexbox – changes the distance between buttons slightly.
* c951968 js: make "Exit Streamer Mode" smoother – fixes a visual glitch when existing Streamer Mode.
* 7c6c85e add version selection dropdown menu – this is the main change of this pull requests. Demo:
https://user-images.githubusercontent.com/624072/110213852-1d852980-7ea2-11eb-8f81-9c194544d394.mp4
=> Add versions dropdown menu

bingo.css, bingo.js, index.html
- The function which hides and shows the bingo sheet has been simplified.
- The size and position of the card shown over hidden sheet has been tweaked.
----
Size and position of the card:
Before:
After:
=> Simplify bingo sheet hiding

bingo.css
Demo:
https://user-images.githubusercontent.com/624072/110219488-ce4df180-7ebf-11eb-9e0c-49b5222bd870.mp4
=> Highlight sliders on hover or click

goals_v4.js
=> Fix spelling of "Nauseous"

bingo.css, bingo.js, index.html
Streamer Mode has been refactored to use a CSS class.
----
The main change is in the last commit of the pull request. Other commits are code cleanup and refactoring.
=> Use CSS for Streamer Mode

bingo.js, index.html
This is a replacement for #55.
=> Store colour count preference in localStorage

generator_v3.js
This is a minor code clean up, which _doesn't change generation_. See details in e323810.
I recommend reviewing with the checkbox "Hide whitespace changes".
=> Simplify generator v3

bingo.js
Only commit 40b93e9 changes the behavior. The other commits are just refactoring.
The change in how "6 Colours" setting works on clicking is the result of [a discussion in Discord](https://discord.com/channels/131720430326120449/333240533138800640/818974022183550987). See also the justification in commit message of 40b93e9.
=> Square colours settings have been refactored and made consistent

README.md
GitHub (and other Git hosting providers) render README files on the
landing page of repositories.  Add a skeleton for the README file with
only the basic information.
=> A README file has been added

bingo.js
This pull requests implements feature request from #67.
=> Shortcut "Q" to clear colours from a square has been added

bingo.js
More settings which should be stored in localStorage are going to be
added in the future.  Settings stored in the localStorage can be managed
one-by-one (as opposed to settings stored in URL).
In preparation of addition of other local settings, refactor
pushNewLocalSetting() to allow saving a specific setting.
=> Saving in localStorage has been prepared for more settings

generator_v3.js
Removed old comments, added new comments
Removed unused variables
Better creation of Indexes array
Added tagCount list which keeps track of tags on the sheet and their amounts instead of recalculating the list/amount by checking every goal on the sheet every time a goal is generated!
Added antisynergy, reactant and catalyst arrays, to keep track of what antisyergys etc are on the sheet instead of checking every goal on the sheet every time a goal is generated!
Refactored check for if the goal is already on the sheet.
Refactored check for same line tag collisions.
Renamed cont to retry, moved it outside the do while loop (how did this even work anyway?).
Removed constant refrences to cont when failing a goal check and instead just set retry to false ONCE at the end of the do while loop is …
=> Refactored generator_v3

bingo.css
=> Text shadow has been added to buttons and slider text

bingo.js
A fix for a bug introduced in #111.
=> Size of the popout bingo card has been fixed

bingo.css, bingo.js, index.html
Before:
After:
https://user-images.githubusercontent.com/624072/112395870-7c023280-8cff-11eb-9240-7b9febb91a32.mp4
=> Options menu has been redesigned. Close #106.
